### ISSUE TITLE
self.feature_dropout not defined

### ISSUE THREAD

**Issue by simonaay** [mxtsai/ELNet#3]
when performing self.feature_dp, it assigns according to self.feature_dropout method which never got initialized. There seems to be code missing or inheriting from a parent class that is not shared in this repo.

**Comment by mxtsai** [comment]
Hi,

Thanks for pointing this out. I've added the following line:`self.feature_dropout = kwargs.get('dropout', 0.0)`. Please pull the latest version for the fix, and specify using the `dropout` key. Thanks.
